### ISSUE TITLE
Feature Request: Specific File Extension Extraction

### ISSUE THREAD

**Issue by TekkaGB** [TGEnigma/preappfile#1]
Not an issue but a feature request because I don't know where else to post it (Sorry if this is the wrong place).  For Aemulus, I'm planning on incorporating preappfile to extract the files used as bases for merging in Persona 4 Golden in order to support the new paths used by cpk redirection in Modloader 1.4.0.  However, I don't need to extract the entirety of the files used by the cpk to use as bases.  Would it be possible to specify file extensions in the commandline arguments to extract only?  For example, I would only need to extract .bin, .pak, .arc, etc.  Files that take a lot of time to extract such as the thousands of .dds files in Persona 4 Golden would be unneeded in my use case.

**Comment by tge-was-taken** [comment]
Would an optional regex match argument be satisfactory?

**Comment by TekkaGB** [comment]
Yes, as long as the regex could be used to match the extension and time is saved by unpacking less files

**Comment by tge-was-taken** [comment]
Addressed by 4049526602455b800dd557ea34e29519408cd60b
